services:
  - type: web
    name: chesspulse-backend
    env: node
    plan: standard
    buildCommand: bash ./render-build.sh && npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "5000"
